import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

const API = import.meta.env.VITE_API_URL || "https://hermes-pro-api-m7wd.onrender.com";
const NAV = [
  ["⌂", "Início"], ["✦", "Hermes"], ["⌁", "Radar"], ["⚗", "Fábrica"], ["◈", "Produtos"], ["▣", "Studio"], ["↗", "Publicação"], ["$", "Vendas"], ["◌", "Analytics"], ["◇", "Experimentos"], ["◎", "Agentes"], ["⟳", "Automação"], ["⌘", "Integrações"], ["≡", "Logs"], ["?", "Guias"]
];
const call = async (path, options = {}) => { const r = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options }); const text = await r.text(); let body = {}; try { body = text ? JSON.parse(text) : {}; } catch { body = { detail: text }; } if (!r.ok) throw new Error(body.detail || `HTTP ${r.status}`); return body; };

function App() {
  const [view, setView] = useState("Início"), [products, setProducts] = useState([]), [jobs, setJobs] = useState([]), [integrations, setIntegrations] = useState([]), [dashboard, setDashboard] = useState({}), [notice, setNotice] = useState(""), [online, setOnline] = useState(false), [topic, setTopic] = useState(""), [chat, setChat] = useState([]), [chatInput, setChatInput] = useState(""), [selected, setSelected] = useState(null), [radar, setRadar] = useState(null), [sales, setSales] = useState(null), [analytics, setAnalytics] = useState(null), [busy, setBusy] = useState(false);
  const refresh = async () => { setBusy(true); try { const [h,d,p,j,i] = await Promise.all([call("/health"),call("/api/v1/dashboard"),call("/api/v1/products"),call("/api/v1/jobs"),call("/api/v1/integrations")]); setOnline(h.status === "ok"); setDashboard(d); setProducts(p); setJobs(j); setIntegrations(i); } catch(e) { setOnline(false); setNotice(e.message); } finally { setBusy(false); } };
  useEffect(() => { refresh(); const id = setInterval(refresh, 8000); return () => clearInterval(id); }, []);
  const action = async (fn, success) => { setBusy(true); try { await fn(); setNotice(success); await refresh(); } catch(e) { setNotice(e.message); } finally { setBusy(false); } };
  const create = e => { e.preventDefault(); if (!topic.trim()) return; action(() => call("/api/v1/products", {method:"POST", body:JSON.stringify({topic:topic.trim()})}).then(x => { setSelected(x); setTopic(""); setView("Jobs"); }), "Produto criado e enviado para a fila."); };
  const chatSend = e => { e.preventDefault(); const text=chatInput.trim(); if(!text)return; setChat(c=>[...c,{role:"user",text}]); setChatInput(""); action(() => call("/api/v1/chat",{method:"POST",body:JSON.stringify({message:text})}).then(x=>setChat(c=>[...c,{role:"assistant",text:x.response}])) , ""); };
  return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">H</div><div><strong>HERMES</strong><span>PRO / COMMAND CENTER</span></div></div><div className="live-pill"><i className={online?"online":"offline"}></i>{online?"SISTEMA ONLINE":"API OFFLINE"}</div><nav>{NAV.map(([icon,label])=><button key={label} className={view===label?"selected":""} onClick={()=>setView(label)}><b>{icon}</b>{label}</button>)}</nav><div className="sidebar-foot"><span>LIVE OPS • v1</span><button onClick={refresh}>↻ Atualizar</button></div></aside><main className="main"><header className="topbar"><div><span className="kicker">HERMES PRO / MONEY OPERATIONS</span><h1>{view}</h1></div><div className="top-actions"><span className="api-label"><i className={online?"online":"offline"}></i>{online?"Backend conectado":"Backend indisponível"}</span><button className="icon-button" onClick={refresh}>↻</button><button className="avatar">W</button></div></header>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}{busy&&<div className="loading-line"><i/> sincronizando dados reais…</div>}
  {view==="Início"&&<Home d={dashboard} products={products} jobs={jobs} go={setView}/>} {view==="Hermes"&&<Chat chat={chat} input={chatInput} setInput={setChatInput} send={chatSend}/>} {view==="Radar"&&<Radar data={radar} run={()=>action(()=>call("/api/v1/radar",{method:"POST",body:JSON.stringify({demand:80,competition:45,differentiation:75,production_difficulty:35,pricing_potential:70,audience_clarity:85})}).then(setRadar),"Radar analisado com dados do motor Hermes.")}/>} {view==="Fábrica"&&<Factory topic={topic} setTopic={setTopic} submit={create}/>} {view==="Produtos"&&<Products items={products} select={setSelected}/>} {view==="Studio"&&<Studio product={selected||products[0]} refresh={refresh} notify={setNotice}/>} {view==="Publicação"&&<Publish product={selected||products[0]} integrations={integrations}/>} {view==="Vendas"&&<Sales data={sales} load={()=>action(()=>call("/api/v1/sales").then(setSales),"Vendas atualizadas.")}/>} {view==="Analytics"&&<Analytics data={analytics} load={()=>action(()=>call("/api/v1/analytics").then(setAnalytics),"Analytics atualizado.")}/>} {view==="Experimentos"&&<Experiments products={products} radar={radar}/>} {view==="Agentes"&&<Agents/>} {view==="Automação"&&<Automation jobs={jobs}/>} {view==="Integrações"&&<Integrations items={integrations}/>} {view==="Logs"&&<Logs jobs={jobs}/>} {view==="Guias"&&<Guides/>}</main></div>;
}
const K=({children})=><span className="kicker violet">{children}</span>; const Button=({children,onClick,primary=false})=><button className={primary?"primary":"text-button"} onClick={onClick}>{children}</button>;
function Home({d,products,jobs,go}){return <Page title="Command Center" sub="Operação comercial com estado real do backend."><section className="hero"><div><K>LIVE PRODUCT ENGINE</K><h2>Ideia → produto → venda.</h2><p>Controle a esteira inteira, sem métricas inventadas.</p><Button primary onClick={()=>go("Fábrica")}>＋ Criar produto</Button></div><div className="hero-orbit"><div className="orbit-center">H<span>AI</span></div><div className="orbit-dot dot-one">✦</div><div className="orbit-dot dot-two">↗</div><div className="orbit-dot dot-three">$</div></div></section><div className="metric-grid"><Metric label="Produtos" value={d.products??0}/><Metric label="Jobs ativos" value={d.active_jobs??0} tone="violet"/><Metric label="Concluídos" value={d.completed_products??0} tone="green"/><Metric label="Vendas" value={d.sales??"—"}/></div><div className="section-heading"><div><K>PIPELINE</K><h3>Estado da fábrica</h3></div><Button onClick={()=>go("Jobs")}>Jobs →</Button></div><div className="panel process-panel"><div className="loop">{["Radar","Estratégia","Conteúdo","Quality","Studio","Oferta","Hotmart"].map((x,i)=><div className="step" key={x}><b>{i+1}</b><span>{x}</span></div>)}</div><p className="panel-note">{jobs.length} jobs persistidos. O sistema não declara publicação ou venda sem confirmação.</p></div><div className="section-heading"><div><K>CATÁLOGO</K><h3>Produtos recentes</h3></div><Button onClick={()=>go("Produtos")}>Abrir →</Button></div><div className="product-row">{products.slice(0,3).map(p=><ProductCard key={p.id} p={p} onClick={()=>{setTimeout(()=>{},0);}}/> )}</div></Page>}
function Metric({label,value,tone=""}){return <article className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>estado persistido</small></article>}
function Page({title,sub,children}){return <section className="page"><div className="page-intro"><K>HERMES PRO</K><h2>{title}</h2><p>{sub}</p></div>{children}</section>}
function Factory({topic,setTopic,submit}){return <Page title="Fábrica" sub="Crie um job real; Gemini e o worker executam as etapas no servidor."><form className="factory-form" onSubmit={submit}><label>Tema do produto<textarea value={topic} onChange={e=>setTopic(e.target.value)} minLength="3" required placeholder="Ex.: guia de marketing digital para MEIs"/></label><div className="form-footer"><span>Redis → Worker → Supabase</span><Button primary>Iniciar produção ↗</Button></div></form><div className="pipeline">{["IDEIA","ESTRATÉGIA","CONTEÚDO","REVISÃO","STUDIO","OFERTA","PUBLICAÇÃO"].map((x,i)=><span key={x}>{i?"→ ":""}{x}</span>)}</div></Page>}
function Products({items,select}){return <Page title="Produtos" sub="Catálogo persistido no Supabase."><div className="product-grid">{items.length?items.map(p=><ProductCard key={p.id} p={p} onClick={()=>select(p)}/>):<Empty text="Nenhum produto ainda."/>}</div></Page>}
function ProductCard({p,onClick}){return <article className="product-card detailed" onClick={onClick}><div className="cover-placeholder"><span>H</span><small>{p.status}</small></div><div className="product-info"><span className="tag">EBOOK</span><h4>{p.title||p.topic}</h4><p>{p.topic}</p><div className="product-meta"><span>stage: {p.current_stage}</span><span>{p.metadata?.quality_score?`${p.metadata.quality_score}/100`:"quality —"}</span></div></div></article>}
function Studio({product,notify,refresh}){const [title,setTitle]=useState(product?.title||""); if(!product)return <Page title="Studio" sub="Selecione um produto no catálogo."/>; const save=()=>actionLocal(()=>call(`/api/v1/products/${product.id}`,{method:"PATCH",body:JSON.stringify({title})}).then(refresh),notify,"Produto atualizado."); function actionLocal(f,s,msg){f().catch(e=>notify(e.message)).then(()=>msg&&notify(msg));} return <Page title="Studio" sub="Edite metadados do produto enquanto o conteúdo é produzido."><div className="panel"><label>Título<input value={title} onChange={e=>setTitle(e.target.value)}/></label><p>Status: <b>{product.status}</b> · etapa: <b>{product.current_stage}</b></p><Button primary onClick={save}>Salvar alterações</Button></div></Page>}
function Radar({data,run}){return <Page title="Radar" sub="Motor de oportunidade. Valores são analisados, não vendidos como certeza."><Button primary onClick={run}>Analisar oportunidade</Button>{data&&<div className="two-col"><div className="panel"><h3>Score {data.score}/100</h3><p>Confiança {data.confidence}%</p>{Object.entries(data.dimensions||{}).map(([k,v])=><div className="health" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="panel"><h3>Findings</h3>{data.findings?.map(x=><p key={x}>• {x}</p>)}</div></div>}</Page>}
function Publish({product,integrations}){return <Page title="Publicação" sub="A publicação fica bloqueada até a integração comercial estar realmente configurada."><div className="panel"><h3>{product?.title||product?.topic||"Nenhum produto selecionado"}</h3><p>Hotmart: <b>{integrations.find(x=>x.name.toLowerCase().includes("hotmart"))?.status||"não verificada"}</b></p><p>Webhook de vendas deve confirmar os eventos antes de Analytics.</p></div></Page>}
function Sales({data,load}){return <Page title="Vendas" sub="Somente eventos reais de venda."><Button primary onClick={load}>Atualizar vendas</Button><div className="metric-grid">{[["Receita",data?.revenue!=null?`R$ ${Number(data.revenue).toFixed(2)}`:"—"],["Pedidos",data?.orders??"—"],["Ticket",data?.ticket!=null?`R$ ${Number(data.ticket).toFixed(2)}`:"—"],["Status",data?.status||"não consultado"]].map(([a,b])=><Metric key={a} label={a} value={b}/>)}</div><div className="panel"><p>{data?.message||"Nenhuma consulta feita ainda."}</p></div></Page>}
function Analytics({data,load}){return <Page title="Analytics" sub="Leitura de dados confirmados; sem receita fictícia."><Button primary onClick={load}>Atualizar analytics</Button><div className="panel">{data?.insights?.map(x=><p key={x}>• {x}</p>)||<p>Faça uma consulta para carregar insights.</p>}</div><div className="panel">{data?.experiments?.map(x=><p key={x}>• {x}</p>)}</div></Page>}
function Experiments({products,radar}){return <Page title="Experimentos" sub="Compare hipóteses de tema, oferta e produto usando os resultados reais disponíveis."><div className="panel"><h3>Próximo experimento</h3><p>{products.length?`${products.length} produtos no catálogo.` : "Crie o primeiro produto."}</p><p>{radar?`Último radar: ${radar.score}/100.` : "Execute o Radar para gerar uma hipótese."}</p></div></Page>}
function Agents(){const a=[["RADAR","Oportunidades"],["STRATEGIST","Estratégia"],["WRITER","Conteúdo"],["EDITOR","Quality"],["DESIGNER","Apresentação"],["PUBLISHER","Publicação"],["GUARDIAN","Proteção"]];return <Page title="Agentes" sub="Cada agente só é considerado ativo quando existe execução real."><div className="agent-grid">{a.map(([n,d])=><article className="agent" key={n}><b>✦</b><div><strong>{n}</strong><p>{d}</p></div><span className="agent-state">backend</span></article>)}</div></Page>}
function Automation({jobs}){return <Page title="Automação" sub="Visão da fila persistente e do worker."><div className="panel"><h3>Fila</h3><p>{jobs.filter(j=>["pending","running","retrying"].includes(j.status)).length} jobs ativos.</p><p>Recovery reprocessa pendências após reinício do worker.</p></div></Page>}
function Integrations({items}){return <Page title="Integrações" sub="Saúde das conexões configuradas no backend."><div className="agent-grid">{items.map(x=><article className="agent" key={x.name}><b>{x.status==="ok"?"✓":"!"}</b><div><strong>{x.name}</strong><p>{x.message}</p></div><span className="agent-state">{x.status}</span></article>)}</div></Page>}
function Logs({jobs}){return <Page title="Logs" sub="Histórico operacional exposto pela persistência de jobs."><div className="job-list">{jobs.map(j=><article className="job" key={j.id}><div className={`job-icon ${j.status}`}>↻</div><div><strong>{j.job_type}</strong><p>{j.error_message||j.id}</p></div><span className={`job-status ${j.status}`}>{j.status}</span><small>{j.attempts}/{j.max_attempts}</small></article>)}</div></Page>}
function Chat({chat,input,setInput,send}){return <Page title="Hermes" sub="Assistente operacional conectado ao AI Gateway."><div className="chat-window">{chat.map((m,i)=><div className={`bubble ${m.role}`} key={i}><span>{m.role}</span><p>{m.text}</p></div>)}{!chat.length&&<div className="chat-empty"><div className="spark">✦</div><h3>Hermes operacional</h3><p>Pergunte sobre a operação ou peça análise.</p></div>}<form className="chat-form" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Fale com Hermes…"/><Button primary>Enviar ↗</Button></form></div></Page>}
function Guides(){return <Page title="Guias" sub="Operação do sistema."><div className="guide-grid"><Guide title="Fábrica" text="Crie um tema e acompanhe o job."/><Guide title="Studio" text="Selecione um produto e ajuste os metadados."/><Guide title="Vendas" text="Apenas eventos confirmados entram no painel."/><Guide title="Integrações" text="Use esta tela para identificar o que ainda falta configurar."/></div></Page>}
function Guide({title,text}){return <article className="panel"><h3>{title}</h3><p>{text}</p></article>}; function Empty({text}){return <div className="panel"><p>{text}</p></div>}
createRoot(document.getElementById("root")).render(<App/>);
