import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

const API = import.meta.env.VITE_API_URL || "https://hermes-pro-api-m7wd.onrender.com";

function App() {
  const [view, setView] = useState("Dashboard");
  const [topic, setTopic] = useState("");
  const [message, setMessage] = useState("");
  const [chat, setChat] = useState([]);
  const [data, setData] = useState({ jobs: 0, products: 0, running: 0, failures: 0, worker: "checking" });
  const [products, setProducts] = useState([]); const [jobs, setJobs] = useState([]);
  async function refresh() { try { const [d, p, j] = await Promise.all([fetch(`${API}/api/v1/dashboard`), fetch(`${API}/api/v1/products`), fetch(`${API}/api/v1/jobs`)]); setData(await d.json()); setProducts(await p.json()); setJobs(await j.json()); } catch { setMessage("API indisponível. Verifique VITE_API_URL e o backend."); } }
  useEffect(() => { refresh(); }, []);
  async function produce(event) { event.preventDefault(); setMessage("Job criado. O worker processará em seguida."); const response = await fetch(`${API}/api/v1/factory/produce`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ topic }) }); if (!response.ok) setMessage("Não foi possível criar o job."); setTopic(""); await refresh(); }
  async function sendChat(event) { event.preventDefault(); const input = event.target.message; const text = input.value.trim(); if (!text) return; setChat(items => [...items, { role: "user", text }]); input.value = ""; const response = await fetch(`${API}/api/v1/chat`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: text }) }); const body = await response.json(); setChat(items => [...items, { role: "assistant", text: response.ok ? body.response : "Hermes não conseguiu responder agora." }]); }
  const nav = ["Dashboard", "Hermes", "Fábrica", "Produtos", "Jobs", "Logs", "Configurações"];
  return <main className="app"><aside><span className="eyebrow">HERMES PRO</span><h1>Control room</h1>{nav.map(item => <button className={view === item ? "active" : ""} onClick={() => setView(item)} key={item}>{item}</button>)}</aside><section className="content"><header><div><span className="eyebrow">OPERATIONS</span><h2>{view}</h2></div><span className="status">Worker: {data.worker}</span></header>{message && <div className="notice">{message}</div>}{view === "Dashboard" && <><div className="cards">{[["Jobs", data.jobs], ["Produtos", data.products], ["Em andamento", data.running], ["Falhas", data.failures]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><p className="muted">Acompanhe produção, jobs e falhas sem dados inventados.</p></>}{view === "Hermes" && <section className="chat"><div className="messages">{chat.length ? chat.map((item, index) => <p className={item.role} key={index}><b>{item.role === "user" ? "Você" : "Hermes"}:</b> {item.text}</p>) : <p className="muted">Converse com Hermes sobre a operação, jobs ou ideias de produtos.</p>}</div><form onSubmit={sendChat}><input name="message" placeholder="Fale com Hermes..." maxLength="4000" /><button className="primary">Enviar</button></form></section>}{view === "Fábrica" && <form onSubmit={produce} className="factory"><label>Tema do produto<input value={topic} onChange={e => setTopic(e.target.value)} placeholder="Ex.: produtividade para equipes remotas" required minLength="3" /></label><button className="primary">Criar job</button><p className="muted">Com Supabase configurado, o worker processa o job, gera o PDF e salva no Storage. Produção autônoma é opt-in no servidor.</p></form>}{view === "Produtos" && <List items={products} empty="Nenhum produto produzido ainda." />}{view === "Jobs" && <List items={jobs} empty="Nenhum job criado ainda." />}{view === "Logs" && <p className="muted">Logs persistentes serão exibidos quando houver eventos registrados.</p>}{view === "Configurações" && <p className="muted">Providers e integrações são configurados no backend. Nenhum secret é carregado no frontend.</p>}</section></main>
}
function List({ items, empty }) { return items.length ? <div className="list">{items.map(item => <pre key={item.id}>{JSON.stringify(item, null, 2)}</pre>)}</div> : <p className="muted">{empty}</p>; }
createRoot(document.getElementById("root")).render(<App />);
